Med_Id.web/Controllers/AuthController.cs
using Med_Id.datamodels;
using Med_Id.viewmodels;
using Med_Id.web.Services;
using Microsoft.AspNetCore.Mvc;

namespace Med_Id.web.Controllers
{
	public class AuthController : Controller
	{
		private AuthService authService;
		VMResponse respon = new VMResponse();

		public AuthController(AuthService _authService)
		{
			this.authService = _authService;
		}

		public IActionResult Login()
		{
			return PartialView();
		}

		public IActionResult Logout()
		{
			HttpContext.Session.Clear();
			return RedirectToAction("Index", "Home");
		}


		[HttpPost]
		public async Task<JsonResult> LoginSubmit(string username)
		{
			//VMUser customer = await authService.CheckLogin(email, password);

			if ( (username == "Admin" || username == "Doctor" || username == "Pasien" || username == "Faskes" || username == "Umum"))
			{
				
				respon.Message = $"Hallo, {username} welcome to XPOS";
				HttpContext.Session.SetString("NameUser", username);
				HttpContext.Session.SetInt32("IdUser", 1);
				if (username == "Admin")
				{
                    HttpContext.Session.SetInt32("IdRole", 1);
                }
                else if (username == "Doctor")
                {
                    HttpContext.Session.SetInt32("IdRole", 2);
                }
                else if (username == "Faskes")
                {
                    HttpContext.Session.SetInt32("IdRole", 3);
                }
                else if (username == "Pasien")
                {
                    HttpContext.Session.SetInt32("IdRole", 4);
                }
                else if (username == "Umum")
                {
                    HttpContext.Session.SetInt32("IdRole", 5);
                }
				else
				{
                    HttpContext.Session.SetInt32("IdRole", 9);
                }

                // username == "Admin" ? 1 : username == "Doctor" ? 2 : username == "Faskes" ? 3 : username == "Pasien" ? 4 : 6
            }
            else
			{
				respon.Message = $"Oops, {username} notfound or password is wrong, please check it!";
			}
			return Json(new { dataRespon = respon });
		}

		//[HttpPost]
		//public async Task<JsonResult> MenuAccess(long IdRole)
		//{
		//	VMUser customer = await authService.MenuAccess(IdRole);

		//	if (customer != null)
		//	{
		//		respon.Message = $"Hallo, {customer.Name} welcome to XPOS";
		//		HttpContext.Session.SetString("NameCustomer", customer.Name);
		//		HttpContext.Session.SetInt32("IdCustomer", customer.Id);
		//		HttpContext.Session.SetInt32("IdRole", customer.RoleId == 1);
		//	}
		//	else
		//	{
		//		respon.Message = "Oops, notfound or password is wrong, please check it!";
		//	}
		//	return Json(new { dataRespon = respon });
		//}
	}
}

Med_Id.web/Controllers/CourierController.cs
using Med_Id.web.Services;
using Microsoft.AspNetCore.Mvc;
using Med_Id.datamodels;
using Med_Id.viewmodels;

namespace Med_Id.web.Controllers
{
    public class CourierController : Controller
    {
        private CourierService courierService;
        private int IdUser = 1;

        public CourierController(CourierService _courierService)
        {
            this.courierService = _courierService;

        }
        public async Task<IActionResult> Index(string sortOrder,
                                                string searchString,
                                                string currentFilter,
                                                int? pageNumber,
                                                int? pageSize)
        {
            ViewBag.CurrentSort = sortOrder;
            ViewBag.CurrentPageSize = pageSize;
            ViewBag.NameSort = string.IsNullOrEmpty(sortOrder) ? "name_desc" : "";

            if (searchString != null)
            {
                pageNumber = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewBag.CurrentFilter = searchString;

            List<MCourier> data = await courierService.GetAllData();

            if (!string.IsNullOrEmpty(searchString))
            {
                data = data.Where(a => a.Name.ToLower().Contains(searchString.ToLower())
                ).ToList();
            }
            switch (sortOrder)
            {
                case "name_desc":
                    data = data.OrderByDescending(a => a.Name).ToList();
                    break;
                default:
                    data = data.OrderBy(a => a.Name).ToList();
                    break;
            }
            return View(PaginationList<MCourier>.CreateAsync(data, pageNumber ?? 1, pageSize ?? 3));
        }

        public IActionResult Create()
        {
            MCourier data = new MCourier();
            return PartialView(data);
        }
        [HttpPost]
        public async Task<IActionResult> Create(MCourier dataParam)
        {
            VMResponse respon = await courierService.Create(dataParam);

            if (respon.Success)
            {
                return Json(new { dataRespon = respon });
            }
            return View(dataParam);
        }
       
        public async Task<IActionResult> Edit(int id)
        {
            MCourier data = await courierService.GetDataById(id);
            return PartialView(data);
        }
        [HttpPost]
        public async Task<IActionResult> Edit(MCourier dataParam)
        {
            VMResponse respon = await courierService.Edit(dataParam);

            if (respon.Success)
            {
                return Json(new { dataRespon = respon });
            }
            return View(dataParam);
        }
        public async Task<IActionResult> Delete(int id)
        {
            MCourier data = await courierService.GetDataById(id);
            return PartialView(data);
        }
        [HttpPost]
        public async Task<IActionResult> SureDelete(int id, int DeletedBy)
        {
            DeletedBy = IdUser;
            VMResponse respon = await courierService.Delete(id, DeletedBy);

            if (respon.Success)
            {
                return RedirectToAction("Index");
            }

            return RedirectToAction("Index", id);
        }
        public async Task<IActionResult> Detail(int id)
        {
            MCourier data = await courierService.GetDataById(id);
            return PartialView(data);
        }
    }
}

Med_Id.web/Controllers/CourierTypeController.cs
using Med_Id.datamodels;
using Med_Id.viewmodels;
using Med_Id.web.Services;
using Microsoft.AspNetCore.Mvc;

namespace Med_Id.web.Controllers
{
    public class CourierTypeController : Controller
    {
        private CourierService courierService;
        private CourierTypeService courierTypeService;
        private int IdUser = 1;

        public CourierTypeController(CourierService _courierService, CourierTypeService _courierTypeService)
        {

            this.courierService = _courierService;
            this.courierTypeService = _courierTypeService;

        }
        public async Task<IActionResult> Index(string sortOrder,
                                                string searchString,
                                                string currentFilter,
                                                int? pageNumber,
                                                int? pageSize)
        {
            ViewBag.CurrentSort = sortOrder;
            ViewBag.CurrentPageSize = pageSize;
            ViewBag.NameSort = string.IsNullOrEmpty(sortOrder) ? "name_desc" : "";

            if (searchString != null)
            {
                pageNumber = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewBag.CurrentFilter = searchString;

            List<VMCourierType> data = await courierTypeService.GetAllData();

            if (!string.IsNullOrEmpty(searchString))
            {
                data = data.Where(a => a.Name.ToLower().Contains(searchString.ToLower())
                ).ToList();
            }
            switch (sortOrder)
            {
                case "name_desc":
                    data = data.OrderByDescending(a => a.Name).ToList();
                    break;
                default:
                    data = data.OrderBy(a => a.Name).ToList();
                    break;
            }
            return View(PaginationList<VMCourierType>.CreateAsync(data, pageNumber ?? 1, pageSize ?? 3));
        }
        public async Task<IActionResult> Create()
        {
            VMCourierType data = new VMCourierType();

            List<MCourier> listCourier = await courierService.GetAllData();
            ViewBag.ListCourier = listCourier;

            return PartialView(data);
        }
        [HttpPost]
        public async Task<IActionResult> Create(VMCourierType dataParam)
        {
            VMResponse respon = await courierTypeService.Create(dataParam);

            if (respon.Success)
            {
                return Json(new { dataRespon = respon });
            }

            return View(dataParam);
        }
        public async Task<IActionResult> Edit(int id)
        {
            VMCourierType data = await courierTypeService.GetDataById(id);

            List<MCourier> listCourier = await courierService.GetAllData();
            ViewBag.ListCourier = listCourier;

            return PartialView(data);
        }
        [HttpPost]
        public async Task<IActionResult> Edit(VMCourierType dataParam)
        {
            VMResponse respon = await courierTypeService.Edit(dataParam);

            if (respon.Success)
            {
                return Json(new { dataRespon = respon });
            }

            return View(dataParam);
        }

        public async Task<IActionResult> Detail(int id)
        {
            VMCourierType data = await courierTypeService.GetDataById(id);

            List<MCourier> listCourier = await courierService.GetAllData();
            ViewBag.ListCourier = listCourier;

            return PartialView(data);
        }
        [HttpPost]
        public async Task<IActionResult> Detail(VMCourierType dataParam)
        {
            VMResponse respon = await courierTypeService.Edit(dataParam);

            if (respon.Success)
            {
                return Json(new { dataRespon = respon });
            }

            return View(dataParam);
        }
        public async Task<IActionResult> Delete(int id)
        {
            VMCourierType data = await courierTypeService.GetDataById(id);
            return PartialView(data);
        }
        [HttpPost]
        public async Task<IActionResult> SureDelete(int id, int DeletedBy)
        {

            VMResponse respon = await courierTypeService.Delete(id, DeletedBy);

            if (respon.Success)
            {
                return RedirectToAction("Index");
            }

            return RedirectToAction("Index", id);
        }
    }
}

Med_Id.web/Views/Shared/_Header.cshtml
@{
	int IdUser = @Context.Session.GetInt32("IdUser") ?? 0;
	string NameUser = @Context.Session.GetString("NameUser") ?? "";
}

<!-- Navbar -->
<nav class="main-header navbar navbar-expand navbar-white navbar-light">
    <!-- Left navbar links -->
    <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
        </li>
        
        
    </ul>
        
    <!-- Right navbar links -->
    <ul class="navbar-nav ml-auto">
        <!-- Navbar Search -->
        <li class="nav-item">
            <a class="nav-link" data-widget="navbar-search" href="#" role="button">
                <i class="fas fa-search"></i>
            </a>
            <div class="navbar-search-block">
                <form class="form-inline">
                    <div class="input-group input-group-sm">
                        <input class="form-control form-control-navbar" type="search" placeholder="Search" aria-label="Search">
                        <div class="input-group-append">
                            <button class="btn btn-navbar" type="submit">
                                <i class="fas fa-search"></i>
                            </button>
                            <button class="btn btn-navbar" type="button" data-widget="navbar-search">
                                <i class="fas fa-times"></i>
                            </button>
                        </div>
                    </div>
                </form>
            </div>
        </li>
		<li class="nav-item">
			@{
				if (IdUser != 0)
				{
					<a class="nav-linkx">
						<span class="ml-2 d-none d-lg-inline-block">
							<span>Hello,</span> <span class="text-dark">@NameUser</span>
							<i data-feather="chevron-down" class="svg-icon"></i>
						</span>
					</a>
				}
				else
				{
					<button class="btn btn-primary btn-lg mt-3" style="border-radius:10px;" id="btn_login">Login</button>

				}
			}
			
        <li class="nav-item">
            @{
                if (IdUser != 0)
                {
                <a class="nav-link" asp-controller="Auth" asp-action="Logout" role="button">
                    <i class="fas fa-power-off"></i>
                </a>
                }
           }
                
        </li>
    </ul>
</nav>
<!-- /.navbar -->

<script>
	$("#btn_login").click(function () {
		//memanggil modal
		$("#myModal_body").empty();
		$("#myModal_body").load("/Auth/Login")
		$("#myModal").modal("show");
	})
</script>

Med_Id.web/Views/Shared/_Layout.cshtml
﻿<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>AdminLTE 3 | Dashboard</title>

    <!-- JQuery -->
    <script src="~/adminlte/plugins/jquery/jquery.min.js"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.js"></script>
    <!-- jQuery UI 1.11.4 -->
    <script src="~/adminlte/plugins/jquery-ui/jquery-ui.min.js"></script>
    <!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->

    <!-- Custom CSS -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.css">

    <!-- Google Font: Source Sans Pro -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="~/adminlte/plugins/fontawesome-free/css/all.min.css">
    <!-- Ionicons -->
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <!-- Tempusdominus Bootstrap 4 -->
    <link rel="stylesheet" href="~/adminlte/plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css">
    <!-- iCheck -->
    <link rel="stylesheet" href="~/adminlte/plugins/icheck-bootstrap/icheck-bootstrap.min.css">
    <!-- JQVMap -->
    <link rel="stylesheet" href="~/adminlte/plugins/jqvmap/jqvmap.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="~/adminlte/dist/css/adminlte.min.css">
    <!-- overlayScrollbars -->
    <link rel="stylesheet" href="~/adminlte/plugins/overlayScrollbars/css/OverlayScrollbars.min.css">
    <!-- Daterange picker -->
    <link rel="stylesheet" href="~/adminlte/plugins/daterangepicker/daterangepicker.css">
    <!-- summernote -->
    <link rel="stylesheet" href="~/adminlte/plugins/summernote/summernote-bs4.min.css">
</head>
<body class="hold-transition sidebar-mini layout-fixed">
    <div class="wrapper">

        <!-- Preloader -->
        <div class="preloader flex-column justify-content-center align-items-center">
            <img class="animation__shake" src="~/adminlte/dist/img/AdminLTELogo.png" alt="AdminLTELogo" height="60" width="60">
        </div>

        <partial name="_Header" />
        <partial name="_Sidebar" />

        <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper">
            
            <section class="content">
                
                    <main role="main" class="pb-3">
                        @RenderBody()
                    </main>
               
            </section>
        </div>

        <footer class="main-footer">
            <strong>Copyright &copy; 2014-2021 <a href="https://adminlte.io">AdminLTE.io</a>.</strong>
            All rights reserved.
            <div class="float-right d-none d-sm-inline-block">
                <b>Version</b> 3.2.0
            </div>
        </footer>
    </div>


    <!-- Modal -->
    <div class="modal fade" id="myModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body" id="myModal_body">
                    ...
                </div>

            </div>
        </div>
    </div>

    <!-- Modal -->
    <div class="modal fade" id="myModal2" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-xl">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body" id="myModal_body2">
                    ...
                </div>

            </div>
        </div>
    </div>


    <!-- Bootstrap 4 -->
    <script src="~/adminlte/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
    <!-- ChartJS -->
    <script src="~/adminlte/plugins/chart.js/Chart.min.js"></script>
    <!-- Sparkline -->
    <script src="~/adminlte/plugins/sparklines/sparkline.js"></script>
    <!-- JQVMap -->
    <script src="~/adminlte/plugins/jqvmap/jquery.vmap.min.js"></script>
    <script src="~/adminlte/plugins/jqvmap/maps/jquery.vmap.usa.js"></script>
    <!-- jQuery Knob Chart -->
    <script src="~/adminlte/plugins/jquery-knob/jquery.knob.min.js"></script>
    <!-- daterangepicker -->
    <script src="~/adminlte/plugins/moment/moment.min.js"></script>
    <script src="~/adminlte/plugins/daterangepicker/daterangepicker.js"></script>
    <!-- Tempusdominus Bootstrap 4 -->
    <script src="~/adminlte/plugins/tempusdominus-bootstrap-4/js/tempusdominus-bootstrap-4.min.js"></script>
    <!-- Summernote -->
    <script src="~/adminlte/plugins/summernote/summernote-bs4.min.js"></script>
    <!-- overlayScrollbars -->
    <script src="~/adminlte/plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js"></script>
    <!-- AdminLTE App -->
    <script src="~/adminlte/dist/js/adminlte.js"></script>
    <!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->

    <script>
        $.widget.bridge('uibutton', $.ui.button)
    </script>

</body>
</html>

Med_Id.web/Views/Shared/_Sidebar.cshtml
@using Med_Id.web.Services
@inject AuthService authService
@{
    int IdUser = @Context.Session.GetInt32("IdUser") ?? 0;
    int IdRole = @Context.Session.GetInt32("IdRole") ?? 0;
    string NameUser = @Context.Session.GetString("NameUser") ?? "";
    var menus = await authService.MenuAccess(IdRole);
}﻿


<!-- Main Sidebar Container -->
<aside class="main-sidebar sidebar-white-primary elevation-4">
    <!-- Brand Logo -->
   

    <!-- Sidebar -->
    <div class="sidebar">
        <!-- Sidebar user panel (optional) -->
        <div class="image d-flex justify-content-center">
                <img src="~/adminlte/dist/img/Logo.png" height="50" width="150" alt="Logo" class="brand-image">            
        </div>

        <!-- Sidebar Menu -->

        <nav class="mt-2">
            <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">

            @foreach (var parent in menus)
            {
                    @if (parent.RoleId == IdRole)
                    {
                        <li class="nav-item menu-open">
                            <a class="nav-link">
                                <i class="nav-icon fas fa-light fa-folder" data-feather="@parent.BigIcon"></i>
                                <span class="hide-menu">@parent.Name</span>
                            </a>

                        </li>
                            @foreach (var child in parent.ListChild)
                            {
                            <li class="nav-item">
                                <a class="nav-link" asp-controller="@child.Name" asp-action="@child.Url">
                                    <i class="far fa-light fa-file nav-icon"></i>
                                    <span class="menu-open">@child.Name</span>
                                </a>
                            </li>


                            }
                    }
            }
            </ul>
@*

            <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
                <!-- Add icons to the links using the .nav-icon class
                     with font-awesome or any other icon font library -->
                <li class="nav-item menu-open">
                    <a href="#" class="nav-link active">
                        <i class="nav-icon fas fa-tachometer-alt"></i>
                        <p>
                            Dashboard
                            <i class="right fas fa-angle-left"></i>
                        </p>
                    </a>
                    <ul class="nav nav-treeview">
                        <li class="nav-item">
                            <a href="./index.html" class="nav-link active">
                                <i class="far fa-circle nav-icon"></i>
                                <p>Dashboard v1</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="./index2.html" class="nav-link">
                                <i class="far fa-circle nav-icon"></i>
                                <p>Dashboard v2</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="./index3.html" class="nav-link">
                                <i class="far fa-circle nav-icon"></i>
                                <p>Dashboard v3</p>
                            </a>
                        </li>
                    </ul>
                </li>
*@




            @*<ul id="sidebarnav">

                @foreach (var parent in menus)
                {
                    <li class="sidebar-item">
                        <a class="sidebar-link has-arrow" href="javascript:void(0)"
                           aria-expanded="false">
                            <i data-feather="@parent.BigIcon" class="feather-icon"></i>
                            <span class="hide-menu">@parent.Name</span>
                        </a>
                        <ul aria-expanded="false" class="collapse first-level base-level-line">

                            @foreach (var child in parent.ListChild)
                            {
                                <li class="sidebar-item">
                                    <a asp-controller="@child.Name" asp-action="@child.Url" class="sidebar-link">
                                        <span class="hide-menu">@child.Name</span>
                                    </a>
                                </li>
                            }

                        </ul>
                    </li>
                }

            </ul>*@
            @*<ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
                <!-- Add icons to the links using the .nav-icon class
                     with font-awesome or any other icon font library -->
                @if (NameUser == "Admin")
                {
                @foreach (var parent in menus)
                {
                    <li class="sidebar-item">
                        <a asp-controller="@parent.Name" asp-action="@parent.Url" class="sidebar-link"> @parent.Name
                            <i class="feather-icon" data-feather="@parent.BigIcon"></i>
                            
                        </a>
                    </li>

                }
                    @if (NameUser == "Doctor")
                    {
                        @foreach (var parent in menus)
                        {
                            <li class="sidebar-item">
                                <a asp-controller="@parent.Name" asp-action="@parent.Url" class="sidebar-link">
                                    @parent.Name
                                    <i class="feather-icon" data-feather="@parent.BigIcon"></i>

                                </a>
                            </li>

                        }

                        <li class="list-divider"></li>
                        <li class="sidebar-item">
                            <a class="sidebar-link sidebar-link" asp-controller="Auth" asp-action="Logout" aria-expanded="false">
                                <i data-feather="log-out" class="feather-icon"></i><span class="hide-menu">Logout</span>
                            </a>
                        </li>

                    }


                    <li class="list-divider"></li>
                    <li class="sidebar-item">
                        <a class="sidebar-link sidebar-link" asp-controller="Auth" asp-action="Logout" aria-expanded="false">
                            <i data-feather="log-out" class="feather-icon"></i><span class="hide-menu">Logout</span>
                        </a>
                    </li>

                }

                    @*<li class="nav-item">
                        <a class="nav-link" asp-controller="Courier" asp-action="Index">
                            <i class="nav-icon fas fa-columns"></i>
                            <p>Courier Page</p>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-controller="CourierType" asp-action="Index">
                            <i class="nav-icon fas fa-columns"></i>
                            <p>Courier Type</p>
                        </a>
                    </li>

                    <li class="nav-header">Transaction</li>
                    <li class="nav-item">
                        <a class="nav-link" asp-controller="Profile" asp-action="Index">
                            <i class="nav-icon fas fa-columns"></i>
                            <p>Profile Doctor</p>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-controller="CourierType" asp-action="Index">
                            <i class="nav-icon fas fa-columns"></i>
                            <p>Detail Profile Doctor</p>
                        </a>
                    </li>

            </ul>*@
                    
                
            
        </nav>
        

        <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
</aside>