Med_Id.web/Controllers/DoctorController.cs
using Med_Id.datamodels;
using Med_Id.viewmodels;
using Med_Id.web.Services;
using Microsoft.AspNetCore.Mvc;

namespace Med_Id.web.Controllers
{
    public class DoctorController : Controller
    {
        private BiodataService biodataService;
        private DoctorService doctorService;
        private int IdUser = 1;

        public DoctorController(DoctorService _doctorService, BiodataService _biodataService)
        {

            this.biodataService = _biodataService;
            this.doctorService = _doctorService;

        }
        public async Task<IActionResult> Index(string sortOrder,
                                                string searchString,
                                                string currentFilter,
                                                int? pageNumber,
                                                int? pageSize)
        {
            ViewBag.CurrentSort = sortOrder;
            ViewBag.CurrentPageSize = pageSize;
            ViewBag.NameSort = string.IsNullOrEmpty(sortOrder) ? "name_desc" : "";

            if (searchString != null)
            {
                pageNumber = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewBag.CurrentFilter = searchString;

            List<VMDoctor> data = await doctorService.GetAllData();

            if (!string.IsNullOrEmpty(searchString))
            {
                data = data.Where(a => a.Fullname.ToLower().Contains(searchString.ToLower())
                || a.Str.ToLower().Contains(searchString.ToLower())
                ).ToList();
            }
            switch (sortOrder)
            {
                case "name_desc":
                    data = data.OrderByDescending(a => a.Fullname).ToList();
                    break;
                default:
                    data = data.OrderBy(a => a.Fullname).ToList();
                    break;
            }
            return View(PaginationList<VMDoctor>.CreateAsync(data, pageNumber ?? 1, pageSize ?? 3));
        }
        public async Task<IActionResult> Create()
        {
            VMDoctor data = new VMDoctor();

            List<MBiodatum> listBiodata = await biodataService.GetAllData();
            ViewBag.ListBiodata = listBiodata;

            return PartialView(data);
        }
        [HttpPost]
        public async Task<IActionResult> Create(VMDoctor dataParam)
        {
            VMResponse respon = await doctorService.Create(dataParam);

            if (respon.Success)
            {
                return Json(new { dataRespon = respon });
            }

            return View(dataParam);
        }
        public async Task<IActionResult> Edit(int id)
        {
            VMDoctor data = await doctorService.GetDataById(id);

            List<MBiodatum> listBiodata = await biodataService.GetAllData();
            ViewBag.ListBiodata = listBiodata;

            return PartialView(data);
        }
        [HttpPost]
        public async Task<IActionResult> Edit(VMDoctor dataParam)
        {
            VMResponse respon = await doctorService.Edit(dataParam);

            if (respon.Success)
            {
                return Json(new { dataRespon = respon });
            }

            return View(dataParam);
        }

        public async Task<IActionResult> Detail(int id)
        {
            VMDoctor data = await doctorService.GetDataById(id);



            List<MBiodatum> listBiodata = await biodataService.GetAllData();
            ViewBag.ListBiodata = listBiodata;

            List<VMTindakanMedis> listTindakanMedis = await doctorService.GetDataByTindakanMedis(id);
            ViewBag.ListTindakanMedis = listTindakanMedis;

            List<VMRiwayatLocation> listRiwayatLocation = await doctorService.GetDataByRiwayatLocation(id);
            ViewBag.ListRiwayatLocation = listRiwayatLocation;

            List<VMLocationPraktek> listLocationPraktek = await doctorService.GetDataByLocationPraktek(id);
            ViewBag.ListLocationPraktek = listLocationPraktek;

            List<VMEducationDoctor> listEducationDoctor = await doctorService.GetDataByEducationDoctor(id);
            ViewBag.ListEducationDoctor = listEducationDoctor;

            return PartialView(data);
        }
        [HttpPost]
        public async Task<IActionResult> Detail(VMDoctor dataParam)
        {
            VMResponse respon = await doctorService.Detail(dataParam);

            if (respon.Success)
            {
                return Json(new { dataRespon = respon });
            }

            return View(dataParam);
        }
        public async Task<IActionResult> Delete(int id)
        {
            VMDoctor data = await doctorService.GetDataById(id);
            return PartialView(data);
        }
        [HttpPost]
        public async Task<IActionResult> SureDelete(int id, int DeletedBy)
        {

            VMResponse respon = await doctorService.Delete(id, DeletedBy);

            if (respon.Success)
            {
                return RedirectToAction("Index");
            }

            return RedirectToAction("Index", id);
        }

       
    }
}

Med_Id.web/Controllers/HomeController.cs
using Med_Id.web.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace Med_Id.web.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Med_Id.web/Views/Home/Index.cshtml
@using Med_Id.web.Services
@inject AuthService authService
@{
    int IdUser = @Context.Session.GetInt32("IdUser") ?? 0;
    int IdRole = @Context.Session.GetInt32("IdRole") ?? 0;
    string NameUser = @Context.Session.GetString("NameUser") ?? "";
    var menus = await authService.MenuAccess(IdRole);
}﻿
<!-- Main content -->
                        <div class="container-fluid justify-content-center">
                            <div class="row">
                             @if (IdRole == 0)
                             {
                                 <div class="col-md-3 col-sm-6 col-12">
                                                <div class="info-box">
                                                    <span class="info-box-icon bg-info"><i class="far fa-envelope"></i></span>

                                                    <div class="info-box-content">
                                                        <a class="nav-link" asp-controller="Home" asp-action="Index"></a>
                                                        <span class="menu-open">Home</span>
                                                    </div>
                                                    <!-- /.info-box-content -->
                                                </div>
                                                <!-- /.info-box -->
                                            </div>

                                            <div class="col-md-3 col-sm-6 col-12">
                                                <div class="info-box">
                                                    <span class="info-box-icon bg-info"><i class="far fa-envelope"></i></span>

                                                    <div class="info-box-content">
                                                        <a class="nav-link" asp-controller="Doctor" asp-action="Index"></a>
                                                        <span class="menu-open">Doctor</span>
                                                    </div>
                                                    <!-- /.info-box-content -->
                                                </div>
                                                <!-- /.info-box -->
                                            </div>

                                            <div class="col-md-3 col-sm-6 col-12">
                                                <div class="info-box">
                                                    <span class="info-box-icon bg-info"><i class="far fa-envelope"></i></span>

                                                    <div class="info-box-content">
                                                        <a class="nav-link" asp-controller="User" asp-action="Index"></a>
                                                        <span class="menu-open">Pendaftaran</span>
                                                    </div>
                                                    <!-- /.info-box-content -->
                                                </div>
                                                <!-- /.info-box -->
                                            </div>

                                            <div class="col-md-3 col-sm-6 col-12">
                                                <div class="info-box">
                                                    <span class="info-box-icon bg-info"><i class="far fa-envelope"></i></span>

                                                    <div class="info-box-content">
                                                        <a class="nav-link" asp-controller="Obat" asp-action="Index"></a>
                                                        <span class="menu-open">Obat</span>
                                                    </div>
                                                    <!-- /.info-box-content -->
                                                </div>
                                                <!-- /.info-box -->
                                            </div>
                             }
                             else if (IdRole != 0)
                             {
                                 @foreach (var parent in menus)
                                {
                                    @if (parent.RoleId == IdRole)
                                    {
                                
                                        @foreach (var child in parent.ListChild)
                                         {
                                             <div class="col-md-3 col-sm-6 col-12">
                                                    <div class="info-box">
                                                        <span class="info-box-icon bg-info"><i class="far fa-envelope"></i></span>

                                                        <div class="info-box-content">
                                                        <a class="nav-link" asp-controller="@child.Name" asp-action="@child.Url"></a>
                                                        <span class="menu-open">@child.Name</span>
                                                        </div>
                                                        <!-- /.info-box-content -->
                                                    </div>
                                                    <!-- /.info-box -->
                                                </div>
                                         }
                                         
                                    }
                                    

                                }
                             }
                           
                            </div>

                </div>
   @*        
@foreach (var parent in menus)
{
    @if (parent.RoleId == IdRole)
    {
        <li class="nav-item menu-open">
            <a class="nav-link">
                <i class="nav-icon fas fa-light fa-folder" data-feather="@parent.BigIcon"></i>
                <span class="hide-menu">@parent.Name</span>
            </a>

        </li>
        @foreach (var child in parent.ListChild)
        {
            <li class="nav-item">
                <a class="nav-link" asp-controller="@child.Name" asp-action="@child.Url">
                    <i class="far fa-light fa-file nav-icon"></i>
                    <span class="menu-open">@child.Name</span>
                </a>
            </li>


        }
    }
}*@